num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
num4 = int(input("Enter the fourth number: "))
num5 = int(input("Enter the fifth number: "))
num6 = int(input("Enter the sixth number: "))
num7 = int(input("Enter the seventh number: "))
num8 = int(input("Enter the eight number: "))
num9 = int(input("Enter the nineth number: "))
num10 = int(input("Enter the tenth number: "))
print("The result is: ", num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10)